//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StatusControl
{
    using System;
    using System.Collections.Generic;
    
    public partial class Highway
    {
        public string Серийный_номер { get; set; }
        public string Название { get; set; }
        public double С_Частота { get; set; }
        public string C_Коэффициент_затухания { get; set; }
        public string C_Технология_передачи_данных { get; set; }
        public string C_Расположение { get; set; }
    }
}
