//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Session2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Access_Networks
    {
        public string Серийный_номер { get; set; }
        public string Наименование { get; set; }
        public int Количество_портов { get; set; }
        public string Стандарт_передачи_данных { get; set; }
        public double Частота { get; set; }
        public string Интерфейсы { get; set; }
        public string Скорость_передачи_данных { get; set; }
        public string Место_расположения { get; set; }
    }
}
