//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Session2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payments
    {
        public System.DateTime Дата_платежа { get; set; }
        public double Сумма_платежа { get; set; }
        public double Баланс_абонента { get; set; }
        public System.DateTime Дата_баланска { get; set; }
        public double Задолженность { get; set; }
        public string Номер_абонента { get; set; }
    }
}
