//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Session2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Suds_Equipment
    {
        public string Серийный_номер { get; set; }
        public string Наименование { get; set; }
        public string Порты { get; set; }
        public string Стандарт_передачи { get; set; }
        public string Скорость { get; set; }
        public string Адрес_абонента { get; set; }
    }
}
